import { OnceDialogueId } from "../types/dialogue.js";

export function isOnceDialogueId(value: unknown): value is OnceDialogueId {
  return [
    "welcome",
    "dugFirstItem",
    "dugFirstBeetle",
    "feedBeetle",
    "buildBeetleHouse",
    "placeStructure",
    "buildWorkshop",
    "craftAxe",
    "buildWoodcutter",
    "woodProduction",
    "buildStonemason",
    "buildKitchen",
    "buildTavern",
    "cookNettleSoup",
    "firstAnt",
    "firstStack",
    "digMoreResources",
    "automateWithAnts",
    "firstGreenfly",
    "firstIronOre",
    "firstLadybug",
    "buildFarm",
    "stonemasonUpgraded",
    "woodcutterUpgraded",
    "buildMushroomField",
    "mushroomField",
    "firstMushroom",
    "firstTermite",
    "termiteMound",
    "automateWithTermites",
    "firstRottenApple",
    "composter",
    "firstSpider",
    "library",
    "townHall",
    "firstBee",
    "beehive",
  ].includes(value as string);
}
