const ASSET_SCALE_FACTOR = 0.3;

export const HOME_BANNER_HEIGHT_PX = 36;
export const GROUND_BG_TILE_WIDTH_PX = 512 * ASSET_SCALE_FACTOR;
export const GROUND_BG_TILE_HEIGHT_PX = 512 * ASSET_SCALE_FACTOR;
